from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('eletronicos', '0001_initial')
    ]

    operations = [
        migrations.RunSQL(
            sql="INSERT INTO eletronicos_produto(nome, descricao, preco, quantidade, avaliacao, imagem) VALUES('Mouse', 'Mouse otimo para games e afins', 10.99, 23, 5, 'https://img2.gratispng.com/20180621/igi/kisspng-computer-mouse-computer-keyboard-gamer-mouse-mats-5b2c65fcd880c6.8251180415296363488868.jpg');INSERT INTO eletronicos_produto(nome, descricao, preco, quantidade, avaliacao, imagem) VALUES('Teclado', 'Teclado otimo para games e afins', 110.99, 2, 4, 'https://toppng.com/uploads/preview/teclado-11563771284s2ttkrfov6.png');INSERT INTO eletronicos_produto(nome, descricao, preco, quantidade, avaliacao, imagem) VALUES('Headset', 'Headset otimo para games e afins', 76.99, 20, 2, 'https://www.imagensempng.com.br/wp-content/uploads/2021/05/Headset-Gamer-Png.png');INSERT INTO eletronicos_produto(nome, descricao, preco, quantidade, avaliacao, imagem) VALUES('Gabinete', 'Gabinete otimo para games e afins', 10.99, 23, 5, 'https://www.imagensempng.com.br/wp-content/uploads/2021/10/Gabinete-gamer-Png-1.png');INSERT INTO eletronicos_produto(nome, descricao, preco, quantidade, avaliacao, imagem) VALUES('Web cam', 'Web cam otimo para games e afins', 22.99, 23, 5, 'https://w7.pngwing.com/pngs/312/255/png-transparent-logitech-webcam-c930e-logitech-c930e-hd-1080p-webcam-video-logitech-webcam-960-000972-webcam.png');INSERT INTO eletronicos_produto(nome, descricao, preco, quantidade, avaliacao, imagem) VALUES('Controle Xbox', 'Controle Xbox otimo para games e afins', 10.99, 23, 5, 'https://w7.pngwing.com/pngs/836/956/png-transparent-xbox-one-controller-kinect-game-controllers-video-game-xbox-electronics-video-game-xbox.png');INSERT INTO eletronicos_produto(nome, descricao, preco, quantidade, avaliacao, imagem) VALUES('Placa de Video', 'Excelente placa de video para seus jogos', 1000.99, 2, 4, 'https://w7.pngwing.com/pngs/759/590/png-transparent-graphics-cards-video-adapters-gddr5-sdram-gigabyte-technology-amd-radeon-500-series-geforce-gtx-electronic-device-geforce-gtx.png');INSERT INTO eletronicos_produto(nome, descricao, preco, quantidade, avaliacao, imagem) VALUES('Monitor', 'Monitor para seus games preferios', 2100.99, 1, 5, 'https://e7.pngegg.com/pngimages/177/836/png-clipart-computer-monitors-aoc-international-display-device-aoc-gamer-sniper-g-60vq6-digital-visual-interface-douglas-c74-globemaster-television-computer-monitor-accessory.png');",
        )
    ]